import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Vancore',
  description: 'Your platform for ...',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background text-black font-sans overflow-x-hidden">
        <main
          className="
            mx-auto w-full max-w-screen-xl
            px-4 sm:px-6 lg:px-8
          "
        >
          {children}
        </main>
      </body>
    </html>
  );
}













/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}*/


