/*import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Vancore',
  description: 'Your platform for ...',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background text-black font-sans overflow-x-hidden">
        <main
          className="
            mx-auto w-full max-w-screen-xl
            px-4 sm:px-6 lg:px-8
          "
        >
          {children}
        </main>
      </body>
    </html>
  );
}*/

// app/layout.tsx
import type { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Vancore',
  description: 'Smart commerce for growing businesses',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden bg-background text-black font-sans">
        {/* 
          You may already have a <Navbar /> sitting ABOVE this <main>.
          We just reserve 4rem (64px) at the top for it.
        */}
        <main
          className="
            mx-auto w-full 
            max-w-screen-2xl 
            px-4 sm:px-6 lg:px-8 
          "
        >
          {children}
        </main>
      </body>
    </html>
  )
}














/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}*/


